graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 109
         y 230
      ]
   ]
   node [
      id 1
      graphics [
         x 332
         y 224
      ]
   ]
   node [
      id 2
      graphics [
         x 458
         y 94
      ]
   ]
   node [
      id 3
      graphics [
         x 625
         y 198
      ]
   ]
   node [
      id 4
      graphics [
         x 500
         y 355
      ]
   ]
   node [
      id 7
      graphics [
         x 643
         y 54
      ]
   ]
   node [
      id 8
      graphics [
         x 777
         y 82
      ]
   ]
   node [
      id 11
      graphics [
         x 340
         y 388
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 2
      target 3
   ]
   edge [
      source 3
      target 4
   ]
   edge [
      source 4
      target 1
   ]
   edge [
      source 2
      target 4
   ]
   edge [
      source 2
      target 7
   ]
   edge [
      source 7
      target 8
   ]
   edge [
      source 4
      target 11
   ]
]