graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 151
         y 295
      ]
   ]
   node [
      id 1
      graphics [
         x 405
         y 79
      ]
   ]
   node [
      id 2
      graphics [
         x 790
         y 201
      ]
   ]
   node [
      id 3
      graphics [
         x 610
         y 397
      ]
   ]
   node [
      id 4
      graphics [
         x 622
         y 241
      ]
   ]
   node [
      id 5
      graphics [
         x 381
         y 364
      ]
   ]
   node [
      id 6
      graphics [
         x 396
         y 178
      ]
   ]
   node [
      id 7
      graphics [
         x 248
         y 372
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 2
      target 3
   ]
   edge [
      source 3
      target 4
   ]
   edge [
      source 4
      target 5
   ]
   edge [
      source 5
      target 6
   ]
   edge [
      source 6
      target 7
   ]
   edge [
      source 7
      target 0
   ]
   edge [
      source 0
      target 6
   ]
   edge [
      source 0
      target 5
   ]
   edge [
      source 0
      target 4
   ]
   edge [
      source 0
      target 2
   ]
   edge [
      source 0
      target 3
   ]
   edge [
      source 7
      target 5
   ]
   edge [
      source 5
      target 3
   ]
   edge [
      source 4
      target 2
   ]
   edge [
      source 1
      target 4
   ]
   edge [
      source 6
      target 4
   ]
   edge [
      source 6
      target 1
   ]
   edge [
      source 6
      target 2
   ]
   edge [
      source 6
      target 3
   ]
   edge [
      source 1
      target 7
   ]
   edge [
      source 1
      target 5
   ]
   edge [
      source 1
      target 3
   ]
   edge [
      source 2
      target 5
   ]
   edge [
      source 2
      target 7
   ]
   edge [
      source 4
      target 7
   ]
   edge [
      source 7
      target 3
   ]
]