graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 122
         y 265
      ]
   ]
   node [
      id 1
      graphics [
         x 269
         y 188
      ]
   ]
   node [
      id 2
      graphics [
         x 293
         y 83
      ]
   ]
   node [
      id 3
      graphics [
         x 131
         y 58
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 2
      target 3
   ]
]