graph [
   comment "Generated by ViSiDiA" 
   node [
      id 0
      graphics [
         x 168
         y 217
      ]
   ]
   node [
      id 1
      graphics [
         x 331
         y 76
      ]
   ]
   node [
      id 2
      graphics [
         x 486
         y 188
      ]
   ]
   node [
      id 3
      graphics [
         x 310
         y 323
      ]
   ]
   edge [
      source 0
      target 1
   ]
   edge [
      source 1
      target 2
   ]
   edge [
      source 2
      target 3
   ]
   edge [
      source 3
      target 0
   ]
   edge [
      source 0
      target 2
   ]
   edge [
      source 1
      target 3
   ]
]